In [ ]:
# AVG ALL SET

In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

In [ ]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3"

In [ ]:
cd /media/datastorage/Phong/cassava/cv/1

/media/datastorage/Phong/cassava/cv/1


In [ ]:
#3 Models
# Set 5
#0.9368
import numpy as np
import os

mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred = (mean_pred1+mean_pred2+mean_pred3+mean_pred4+mean_pred5)/5

In [ ]:
#Cassava_NonGrp_Set3_T1_3M_STD

In [ ]:
mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_0Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
# mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred = (mean_pred1+mean_pred2+mean_pred3+mean_pred4+mean_pred5)/5

In [ ]:
mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_3Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
# mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred = (mean_pred1+mean_pred2+mean_pred3+mean_pred4+mean_pred5)/5

In [ ]:
mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
# mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_3Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
# # mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred = (mean_pred4+mean_pred5)/2

In [ ]:
mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_3Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
# # mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred = (mean_pred3+mean_pred4+mean_pred5)/3

In [ ]:
mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
# mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_3Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred = (mean_pred3+mean_pred4+mean_pred5)/3

In [ ]:
# # mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy'))

In [ ]:
m3_1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_3Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
m3_2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_3Crop_Xception_LRG501_Mul_STD.npy'))
m3_3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_0Crop_IcpResNetV2_LRG501_Mul_STD_L3.npy'))
mean_pred3 = (m3_1+m3_2+m3_3)/3                       

In [ ]:
#0.9333
import numpy as np
import os

mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
# mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))

mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_T1_3Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
mean_pred = (mean_pred1+mean_pred2+mean_pred3+mean_pred4+mean_pred5)/5

In [ ]:
mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
# mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_T1_3Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
# mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
# mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred = (mean_pred3+mean_pred4+mean_pred5)/3

In [ ]:
mean_pred = mean_pred3

In [ ]:
#0.9333
import numpy as np
import os

mean_pred5 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set5_M3_L2_LRG501_Mul_STD.npy'))
mean_pred4 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set4_T1_3M_STD.npy'))
mean_pred3 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set3_0Crop_SEResNext101_LRG501_Mul_STD.npy'))
mean_pred2 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set2_3Crop_SEResNext101_LRG501_Mul_STD.npy'))

mean_pred1 = np.load(os.path.join('pred_npy','Cassava_NonGrp_Set1_T1_3Crop_SEResNext101_LRG501_Mul_STD_L3.npy'))
mean_pred = (mean_pred1+mean_pred2+mean_pred3+mean_pred4+mean_pred5)/5

In [ ]:
from keras.preprocessing.image import ImageDataGenerator
from math import ceil
import numpy as np

batch_size = 20

#Crop-Official Test
def random_crop(img, random_crop_size):
    # Note: image_data_format is 'channel_last'
    assert img.shape[2] == 3
    height, width = img.shape[0], img.shape[1]
    dy, dx = random_crop_size
    x = np.random.randint(0, width - dx + 1)
    y = np.random.randint(0, height - dy + 1)
    return img[y:(y+dy), x:(x+dx), :]

def crop_generator(batches, crop_length):
    """Generate random crops from the image batches"""
    while True:
        batch_x, batch_y = next(batches)
        batch_crops = np.zeros((batch_x.shape[0], crop_length, crop_length, 3))
        for i in range(batch_x.shape[0]):
            batch_crops[i] = random_crop(batch_x[i], (crop_length, crop_length))
        yield (batch_crops, batch_y)

train_datagen = ImageDataGenerator(

)

train_set = train_datagen.flow_from_directory('train_3',
                                                 target_size = (501, 501),
                                                 batch_size = batch_size,
                                                 class_mode = 'categorical',
                                                 shuffle=True,
                                                 seed=7,
#                                                  subset="training"
                                              )
        
test_datagen_crop = ImageDataGenerator(
)

testing_set_crop = test_datagen_crop.flow_from_directory('test',
                                                 target_size = (540, 540),
                                                 batch_size = batch_size,
                                                 class_mode = 'categorical',
                                                 shuffle=False,
                                                 seed=7,
#                                                  subset="training"
                                              )
#customized generator
test_crops = crop_generator(testing_set_crop, 501)

step_size_test_crop = ceil(testing_set_crop.n/testing_set_crop.batch_size)

predicted_class_indices_mean=np.argmax(mean_pred,axis=1)
labels = (train_set.class_indices)
labels = dict((v,k) for k,v in labels.items())
finalpre = [labels[k] for k in predicted_class_indices_mean]

import pandas as pd
filenames=testing_set_crop.filenames
results=pd.DataFrame({"id":filenames,
                      "predicted":finalpre,
                      })
results.to_csv('Cassava_NonGrp_MulModels540_2808_v10.csv')
results.head(10)

Found 4527 images belonging to 5 classes.
Found 3774 images belonging to 1 classes.


id predicted
0     0/test-img-0.jpg      cbsd
1     0/test-img-1.jpg      cbsd
2    0/test-img-10.jpg       cmd
3   0/test-img-100.jpg       cgm
4  0/test-img-1000.jpg      cbsd
5  0/test-img-1001.jpg       cmd
6  0/test-img-1002.jpg       cmd
7  0/test-img-1003.jpg       cmd
8  0/test-img-1004.jpg       cmd
9  0/test-img-1005.jpg       cgm

In [ ]:
cp Cassava_NonGrp_MulModels540_2808_v10.csv /home/bribeiro/Phong/Nat19/Cassava_NonGrp_MulModels540_2808_v10.csv

In [ ]:
# cp pred_npy/Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD.npy pred_npy/Cassava_NonGrp_Set1_3Crop_SEResNext101_LRG501_Mul_STD_bkp.npy

In [ ]:
cp checkpoints/Cassava_NonGrp_Set1_SEResNext101_LRG501_Mul_STD.pkl checkpoints/Cassava_NonGrp_Set1_SEResNext101_LRG501_Mul_STD_bkp.pkl

In [ ]:
mean_pred = []

In [ ]:
mean_pred.append(mean_pred5)

In [ ]:
mean_pred.append(mean_pred4)

In [ ]:
mean_pred.append(mean_pred3)

In [ ]:
mean_pred.append(mean_pred2)

In [ ]:
mean_pred.append(mean_pred1)

In [ ]:
from keras.preprocessing.image import ImageDataGenerator
from math import ceil
import numpy as np

batch_size = 20

#Crop-Official Test
def random_crop(img, random_crop_size):
    # Note: image_data_format is 'channel_last'
    assert img.shape[2] == 3
    height, width = img.shape[0], img.shape[1]
    dy, dx = random_crop_size
    x = np.random.randint(0, width - dx + 1)
    y = np.random.randint(0, height - dy + 1)
    return img[y:(y+dy), x:(x+dx), :]

def crop_generator(batches, crop_length):
    """Generate random crops from the image batches"""
    while True:
        batch_x, batch_y = next(batches)
        batch_crops = np.zeros((batch_x.shape[0], crop_length, crop_length, 3))
        for i in range(batch_x.shape[0]):
            batch_crops[i] = random_crop(batch_x[i], (crop_length, crop_length))
        yield (batch_crops, batch_y)

train_datagen = ImageDataGenerator(

)

train_set = train_datagen.flow_from_directory('train_5',
                                                 target_size = (501, 501),
                                                 batch_size = batch_size,
                                                 class_mode = 'categorical',
                                                 shuffle=True,
                                                 seed=7,
#                                                  subset="training"
                                              )
        
test_datagen_crop = ImageDataGenerator(
)

testing_set_crop = test_datagen_crop.flow_from_directory('test',
                                                 target_size = (540, 540),
                                                 batch_size = batch_size,
                                                 class_mode = 'categorical',
                                                 shuffle=False,
                                                 seed=7,
#                                                  subset="training"
                                              )
#customized generator
test_crops = crop_generator(testing_set_crop, 501)

step_size_test_crop = ceil(testing_set_crop.n/testing_set_crop.batch_size)

predicted_class_indices_mean=np.argmax(mean_pred,axis=1)
labels = (train_set.class_indices)
labels = dict((v,k) for k,v in labels.items())
finalpre = [labels[k] for k in predicted_class_indices_mean]

import pandas as pd
filenames=testing_set_crop.filenames
results=pd.DataFrame({"id":filenames,
                      "predicted":finalpre,
                      })
results.to_csv('Cassava_NonGrp_MulModels540_2608_v18.csv')
results.head(10)

Found 4527 images belonging to 5 classes.
Found 3774 images belonging to 1 classes.


id predicted
0     0/test-img-0.jpg      cbsd
1     0/test-img-1.jpg      cbsd
2    0/test-img-10.jpg       cmd
3   0/test-img-100.jpg       cgm
4  0/test-img-1000.jpg      cbsd
5  0/test-img-1001.jpg       cmd
6  0/test-img-1002.jpg       cmd
7  0/test-img-1003.jpg       cmd
8  0/test-img-1004.jpg       cmd
9  0/test-img-1005.jpg       cgm

In [ ]:
cp Cassava_NonGrp_MulModels540_2608_v18.csv /home/bribeiro/Phong/Nat19/Cassava_NonGrp_MulModels540_2608_v18.csv

In [ ]:
print(predicted_class_indices_mean)

[[2871 3283  370 1983 3183]
 [1178  417  952  674 2199]
 [3366 1868  952  369 1126]
 [ 576 1887 2890 1077  413]
 [1042 2192  370  677 3183]]


In [ ]:
print(mean_pred5)

[[7.2487252e-04 9.8896933e-01 1.0173460e-02 8.3752675e-05 4.8574828e-05]
 [2.2832712e-03 9.9491137e-01 2.2981958e-03 4.8259625e-04 2.4632920e-05]
 [1.2129356e-02 3.9386909e-02 4.8047924e-01 4.6745443e-01 5.5008027e-04]
 ...
 [2.1687758e-05 5.8596060e-03 9.9397594e-01 1.4108299e-04 1.6413582e-06]
 [8.1261871e-03 3.7213583e-03 1.8585259e-02 9.4332904e-01 2.6238183e-02]
 [4.5832782e-03 7.9097033e-02 1.4678237e-02 9.0130669e-01 3.3476728e-04]]


In [ ]:
mean_pred = (mean_pred1+mean_pred2+mean_pred3+mean_pred4+mean_pred5)/5
print(mean_pred)

[[9.6522056e-04 9.8142862e-01 1.4068015e-02 6.6054368e-04 2.8776231e-03]
 [5.6501431e-03 9.9319887e-01 6.5908872e-04 4.5718258e-04 3.4691500e-05]
 [8.9761121e-03 1.9519504e-02 1.0516248e-01 8.6620486e-01 1.3697715e-04]
 ...
 [1.2137207e-03 1.2587723e-03 9.9749452e-01 3.2582342e-05 4.5947164e-07]
 [2.2981330e-03 6.0854603e-02 1.8602373e-02 9.1255158e-01 5.6933006e-03]
 [1.3754439e-03 5.8712386e-02 3.2648563e-02 9.0717393e-01 8.9703462e-05]]


In [ ]:
print(mean_pred)

[array([[7.2487252e-04, 9.8896933e-01, 1.0173460e-02, 8.3752675e-05,
        4.8574828e-05],
       [2.2832712e-03, 9.9491137e-01, 2.2981958e-03, 4.8259625e-04,
        2.4632920e-05],
       [1.2129356e-02, 3.9386909e-02, 4.8047924e-01, 4.6745443e-01,
        5.5008027e-04],
       ...,
       [2.1687758e-05, 5.8596060e-03, 9.9397594e-01, 1.4108299e-04,
        1.6413582e-06],
       [8.1261871e-03, 3.7213583e-03, 1.8585259e-02, 9.4332904e-01,
        2.6238183e-02],
       [4.5832782e-03, 7.9097033e-02, 1.4678237e-02, 9.0130669e-01,
        3.3476728e-04]], dtype=float32), array([[1.14167354e-03, 9.91292894e-01, 6.21548574e-03, 6.40222977e-04,
        7.09746790e-04],
       [2.27560457e-02, 9.76203680e-01, 6.85587234e-04, 2.43335191e-04,
        1.11334426e-04],
       [3.14941956e-03, 2.44147629e-02, 5.67656709e-03, 9.66741204e-01,
        1.79596500e-05],
       ...,
       [2.90619737e-05, 5.52544293e-07, 9.99969721e-01, 6.96344500e-07,
        4.01565146e-08],
       [2.72988909